Adds deploy to CI
scriptkitty/ipfs-metric-exporter pull request #29
Opened 2022-06-08 11:21 UTC by lgehr

as discussed

2022-06-08 13:50 UTC, lgehr commented
I think the CI only fails, because it can not create tags in this environment. We should merge 
(also it works on my repo...)

2022-06-08 13:54 UTC, mrd0ll4r approved these changes

2022-06-08 15:06 UTC, mrd0ll4r requested changes

2022-06-08 15:06 UTC, mrd0ll4r commented on .github/workflows/Build_release.yaml
> +    - name: Setup
I guess we don't actually need Go outside of the container, right?

2022-06-08 15:06 UTC, mrd0ll4r commented on .github/workflows/Lint_Build.yaml
> -    - name: Build Docker Image
Let's leave this in here, I want this tested on PRs :)

2022-06-10 10:37 UTC, mrd0ll4r approved these changes
LGMT, ship it!

2022-06-10 10:37 UTC, merged